version: "3.8"
services:
  postgres:
    container_name: "postgres"
    image: "postgres:15-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "mozza"
